"""
Step 6 of the workflow - Send the generated content via Gmail.
"""

import html as html_module
import smtplib
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from config import EMAIL_RECIPIENT, GMAIL_ADDRESS, GMAIL_APP_PASSWORD


def _scrub_dashes(text: str) -> str:
    """Strip em/en dashes per Voice DNA HARD RULE. Em -> ' - ', En -> '-'."""
    return text.replace("—", " - ").replace("–", "-")


def _format_post_for_html(text: str) -> str:
    """Convert plain post text to email-safe HTML body.

    - Strips em/en dashes (Voice DNA HARD RULE).
    - HTML-escapes special characters.
    - Converts \\n to <br> because Gmail strips inline white-space:pre-wrap
      and would otherwise collapse newlines into spaces, rendering the post
      as one giant paragraph.
    """
    text = _scrub_dashes(text)
    text = html_module.escape(text)
    text = text.replace("\n", "<br>")
    return text


def _get_recipients(recipient: str = "") -> list[str]:
    """Parse recipient string (comma-separated) into a list of emails."""
    raw = recipient or EMAIL_RECIPIENT
    return [r.strip() for r in raw.split(",") if r.strip()]


def send_email(
    subject: str,
    post_text: str,
    image_bytes: bytes | None = None,
    recipient: str = "",
) -> None:
    """
    Send a single LinkedIn post draft via Gmail SMTP.
    """
    recipients = _get_recipients(recipient)
    if not all([GMAIL_ADDRESS, GMAIL_APP_PASSWORD, recipients]):
        raise ValueError(
            "Gmail credentials or recipient not configured. "
            "Check GMAIL_ADDRESS, GMAIL_APP_PASSWORD, and EMAIL_RECIPIENT in .env."
        )

    msg = MIMEMultipart("related")
    msg["From"] = GMAIL_ADDRESS
    msg["To"] = ", ".join(recipients)
    msg["Subject"] = subject

    # Build HTML body
    post_html = _format_post_for_html(post_text)
    html = f"""\
    <html>
    <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #0077B5;">Your LinkedIn Post is Ready.</h2>
        <div style="background: #f3f6f8; padding: 20px; border-radius: 8px;
                    border-left: 4px solid #0077B5; line-height: 1.6;">
{post_html}
        </div>
        <br>
        {"<h3>Suggested Image:</h3><img src='cid:post_image' style='max-width:100%; border-radius:8px;'>" if image_bytes else ""}
        <hr style="margin-top: 30px;">
        <p style="color: #666; font-size: 12px;">
            Generated by <strong>LinkedIn Content Generator</strong><br>
            Copy the text above and paste it into LinkedIn, or schedule it
            with your favorite social-media scheduler.
        </p>
    </body>
    </html>
    """
    msg.attach(MIMEText(html, "html"))

    # Attach image inline if available
    if image_bytes:
        img_part = MIMEImage(image_bytes, _subtype="png")
        img_part.add_header("Content-ID", "<post_image>")
        img_part.add_header("Content-Disposition", "inline", filename="linkedin_post.png")
        msg.attach(img_part)

    print(f"[Gmail] Sending email to {', '.join(recipients)}...")
    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(GMAIL_ADDRESS, GMAIL_APP_PASSWORD)
        server.send_message(msg)

    print("[Gmail] Email sent successfully.")


def send_n_options_email(
    subject: str,
    options: list[tuple[str, str]],
    images: list[bytes | None],
    recipient: str = "",
) -> None:
    """
    Send an email with N LinkedIn post options to choose from.
    options: list of (theme_name, post_text). Length determines option count.
    images: list of image bytes (or None) for each option (same length as options).

    Bumped to N (variable) on 2026-05-28 from the hard-coded 3-option flow.
    Header text and "reply with" instructions adapt to actual count.
    """
    n = len(options)
    if n == 0:
        raise ValueError("send_n_options_email called with zero options.")

    recipients = _get_recipients(recipient)
    if not all([GMAIL_ADDRESS, GMAIL_APP_PASSWORD, recipients]):
        raise ValueError(
            "Gmail credentials or recipient not configured. "
            "Check GMAIL_ADDRESS, GMAIL_APP_PASSWORD, and EMAIL_RECIPIENT in .env."
        )

    msg = MIMEMultipart("related")
    msg["From"] = GMAIL_ADDRESS
    msg["To"] = ", ".join(recipients)
    msg["Subject"] = subject

    # Build HTML for all N options
    options_html = ""
    for i, ((theme_name, post_text), img_bytes) in enumerate(zip(options, images), 1):
        img_tag = f'<img src="cid:post_image_{i}" style="max-width:100%; border-radius:8px; margin-top:10px;">' if img_bytes else ""
        theme_html = html_module.escape(_scrub_dashes(theme_name))
        post_html = _format_post_for_html(post_text)
        options_html += f"""
        <div style="margin-bottom: 40px;">
            <h2 style="color: #0077B5; border-bottom: 2px solid #0077B5; padding-bottom: 8px;">
                Option {i}: {theme_html}
            </h2>
            <div style="background: #f3f6f8; padding: 20px; border-radius: 8px;
                        border-left: 4px solid #0077B5; line-height: 1.6; font-size: 14px;">
{post_html}
            </div>
            {img_tag}
        </div>
        """

    pick_choices = ", ".join(str(i) for i in range(1, n + 1))
    html = f"""\
    <html>
    <body style="font-family: Arial, sans-serif; max-width: 700px; margin: 0 auto;">
        <div style="background: #0077B5; color: white; padding: 20px; border-radius: 8px 8px 0 0; text-align: center;">
            <h1 style="margin: 0;">Pick Your LinkedIn Post</h1>
            <p style="margin: 5px 0 0 0; opacity: 0.9;">{n} options below. Reply with your choice ({pick_choices})</p>
        </div>

        <div style="padding: 20px;">
            {options_html}
        </div>

        <div style="background: #f0f0f0; padding: 15px; border-radius: 0 0 8px 8px; text-align: center;">
            <p style="color: #666; font-size: 13px; margin: 0;">
                <strong>Reply to this email with {pick_choices}</strong> to approve a post.<br>
                Generated by <strong>LinkedIn Content Generator</strong> | G Squared Truths + Idea Source
            </p>
        </div>
    </body>
    </html>
    """
    msg.attach(MIMEText(html, "html"))

    # Attach images inline
    for i, img_bytes in enumerate(images, 1):
        if img_bytes:
            img_part = MIMEImage(img_bytes, _subtype="png")
            img_part.add_header("Content-ID", f"<post_image_{i}>")
            img_part.add_header("Content-Disposition", "inline", filename=f"option_{i}.png")
            msg.attach(img_part)

    print(f"[Gmail] Sending {n} options to {', '.join(recipients)}...")
    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(GMAIL_ADDRESS, GMAIL_APP_PASSWORD)
        server.send_message(msg)

    print(f"[Gmail] Email with {n} options sent successfully.")


def send_three_options_email(
    subject: str,
    options: list[tuple[str, str]],
    images: list[bytes | None],
    recipient: str = "",
) -> None:
    """
    Legacy entry point. Kept so older scripts that import this still work.
    Forwards to send_n_options_email which handles any N.
    """
    return send_n_options_email(subject, options, images, recipient)
