"""
Step 6 of the workflow — Send the generated content via Gmail.
"""

import smtplib
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from config import EMAIL_RECIPIENT, GMAIL_ADDRESS, GMAIL_APP_PASSWORD


def send_email(
    subject: str,
    post_text: str,
    image_bytes: bytes | None = None,
    recipient: str = "",
) -> None:
    """
    Send the generated LinkedIn post (and optional image) via Gmail SMTP.
    """
    recipient = recipient or EMAIL_RECIPIENT
    if not all([GMAIL_ADDRESS, GMAIL_APP_PASSWORD, recipient]):
        raise ValueError(
            "Gmail credentials or recipient not configured. "
            "Check GMAIL_ADDRESS, GMAIL_APP_PASSWORD, and EMAIL_RECIPIENT in .env."
        )

    msg = MIMEMultipart("related")
    msg["From"] = GMAIL_ADDRESS
    msg["To"] = recipient
    msg["Subject"] = subject

    # Build HTML body
    html = f"""\
    <html>
    <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #0077B5;">Your LinkedIn Post is Ready!</h2>
        <div style="background: #f3f6f8; padding: 20px; border-radius: 8px;
                    border-left: 4px solid #0077B5; white-space: pre-wrap;">
{post_text}
        </div>
        <br>
        {"<h3>Suggested Image:</h3><img src='cid:post_image' style='max-width:100%; border-radius:8px;'>" if image_bytes else ""}
        <hr style="margin-top: 30px;">
        <p style="color: #666; font-size: 12px;">
            Generated by <strong>LinkedIn Content Generator</strong><br>
            Copy the text above and paste it into LinkedIn, or schedule it
            with your favorite social-media scheduler.
        </p>
    </body>
    </html>
    """
    msg.attach(MIMEText(html, "html"))

    # Attach image inline if available
    if image_bytes:
        img_part = MIMEImage(image_bytes, _subtype="png")
        img_part.add_header("Content-ID", "<post_image>")
        img_part.add_header("Content-Disposition", "inline", filename="linkedin_post.png")
        msg.attach(img_part)

    print(f"[Gmail] Sending email to {recipient}...")
    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(GMAIL_ADDRESS, GMAIL_APP_PASSWORD)
        server.send_message(msg)

    print("[Gmail] Email sent successfully!")
